### ISSUE TITLE
Sparse datasets

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/n5-imglib2#2]
`N5Utils.open` (or a separate method, e.g. `N5Utils.openSparse`) should populate blocks in memory with a (user-specified) default value if the reader cannot find a block at the requested location.

**Comment by axtimwalde** [comment]
Alternative, have a default value for the dataset or in the `DatasetAttributes` respectively.  Not entirely sure how to make this as nice as possible for the various types.  It's probably simple, but didn't have time to think about it in detail.

**Comment by hanslovsky** [comment]
I think we should be flexible as reading a default value from the attributes, using a value specified at runtime, and throwing an exception are all useful and do have their use cases. One way to achieve that is to add a *failure handler* to the [`N5CellLoader.load`](https://github.com/saalfeldlab/n5-imglib2/blob/master/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5CellLoader.java#L64). This failure handler can handle the exception (and the case that `block == null`), and either:
 1. re-throw the exception (same behavior as now)
 2. read default value from attributes (and throw if it doesn't exist)
 3. use default value specified at runtime
 4. other behavior can be implemented as desired
By default, we should use (1).
I like this because it would give a lot of flexibility in how we handle missing data.

**Comment by hanslovsky** [comment]
I added an example implementation in aa29859
There are a few things to consider:
 - Should we invoke the special case handler
    - [whenever an exception is thrown](https://github.com/hanslovsky/n5-imglib2/blob/aa29859e472814b0930ebbf3539d17a34c81ead4/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5CellLoader.java#L70-L73),
    - or only when `N5Reader.readBlock` returns null?
 If we decide for the latter, the [JavaDoc](https://github.com/saalfeldlab/n5/blob/e669549e404ae52f34c650d2b4d53726e0a9c8f5/src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java#L234) should specify that `N5Reader.readBlock` returns null if a file is not found (or equivalent for readers that are not `N5FSReader`).
 - I will add JavaDoc for the new `ExceptionHandlers` once we decide that this is ready for a PR.

**Comment by igorpisarev** [comment]
I like the idea of invoking the missing data handler only if `N5Reader.readBlock` returns `null` and making this clear in the N5 javadoc & spec. Otherwise, swallowing exceptions can be misleading for tracking down the problem (for example, cloud implementations may throw exceptions due to incorrect credentials/permissions or network errors).

**Comment by hanslovsky** [comment]
Updated to regard only null pointers as missing blocks in sparse dataset in 2f00559e
This is the diff:
https://github.com/saalfeldlab/n5-imglib2/compare/master...hanslovsky:sparse?expand=1

**Comment by hanslovsky** [comment]
I like that this would allow to throw an exception when `N5Reader.readBlock` returns `null`, which is desired behavior for some use cases.

**Comment by hanslovsky** [comment]
Resolved in #3.
