### ISSUE TITLE
Example script for saving?

### ISSUE THREAD

**Issue by haesleinhuepf** [saalfeldlab/n5-imglib2#31]
Hi @bogovicj ,

I like your example script for opening and showing n5 data!
https://github.com/saalfeldlab/n5-imglib2/blob/master/scripts/open-and-show.bsh

Is there also an example script somewhere that shows how to save a dataset? Simple example: Open-ApplyGaussianBlur-Save?

Thanks!

Best,
Robert

**Comment by bogovicj** [comment]
Good point, @haesleinhuepf
I'll make one

**Comment by bogovicj** [comment]
Two demos for the price of one.

Using n5-imglib2's `N5Utils` 
https://github.com/saalfeldlab/n5-imglib2/blob/master/scripts/readProcessWriteDemo.bsh

Using n5-ij's `N5IJUtils` 
https://github.com/saalfeldlab/n5-ij/blob/master/scripts/readProcessWriteIJDemo.bsh

I'll link to these in the README's as well.
Thanks for the poke @haesleinhuepf  :smile:

**Comment by haesleinhuepf** [comment]
Wonderful @bogovicj , thank you! 😃
